### ISSUE TITLE
Comments should be renamed "Private Messages" in the simplified Comments+Private Messages interface

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/globaleaks-whistleblowing-software#1015]
it has been suggested by an adopert (wildleaks) to change the name of the "Comments" label to "Private Messages" under the conditions of a single receiver subscribed onto the platform.

Currently what happens is:
Complete Interface: Comments + Private messages
Simplified Interface: Only "Comments"

The change will involve instead showing:
Complete Interface: Comments + Private messages (as now)
Simplified Interface: Only "Private Messages"

The reasons behind this suggestion is that Whistleblowers seem to be more attracted by a private messaging while if they see simply written "Comments" they are discouraged to take the action.

**Comment by evilaliv3** [comment]
related to this ticket i've applied a new change.
the two interfaces (if enabled) are both visible also if only one receiver is present.
this is needed due to the fact that system messages are only shown here as suggested to me by @2langnic

**Comment by evilaliv3** [comment]
we will make the optimization in the future when system messages will be shown in a different way (eventually removing them from the messages workflo and putting them in a dedicated handler+interface)

**Comment by fpietrosanti** [comment]
@evilaliv3 it's a regression bug to re-enable both. Can't we just make it configurable? Otherwise, the next upgrade of GlobaLeaks will reintroduce the bug of having the two interface together. 
IMHO System messages have minor relevance, compared to the usability bug we already experienced in having the two interface together.

**Comment by evilaliv3** [comment]
ok so what i'm going to do is the following.
1) change the fix i've applied
2) remove also  the system messagese as already implemented and mixed with user comments.

the system notifications will be implementetd in a clean way and it's also possible they wont be important in the short term after we will have improved the ui with amnesry ideas.
