### ISSUE TITLE
Counting access to /tip resource

### ISSUE THREAD

**Issue by hellais** [globaleaks/globaleaks-whistleblowing-software#110]
Currently we increment the access counter only when a request is done to the `/tip` resource. This means that a Receiver is able to view the number of accesses performed by other receivers without incrementing their own access counter.

This kind of behavior lead to #104.

Perhaps this is not an issue, but it's something we should think about and if we decide to leave it this way, document it.

**Comment by vodkina** [comment]
What about this issue?!
