### ISSUE TITLE
Context allow switches should disable API POSTs

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/globaleaks-whistleblowing-software#1818]
The handlers related to messages and comments do not prevent a user from leaving messages and comments even when the context based switches are set to disabled.

Noticed this when implementing WB File uploads.

This is a very simple issue to solve. Here is the example from wbfile: 

```python
class WhistleblowerFileHandler(BaseHandler):

        ...

        def post(rtip_id):
        ...
            if not rtip.internaltip.context.enable_rc_to_wb_files:
                raise errors.ForbiddenOperation('Cannot attach wb_files')

```

**Comment by GuilhermeRameh** [comment]
Hi, is this issue still available to work on? i would like to contribute!

**Comment by evilaliv3** [comment]
Hello @GuilhermeRameh , this is a quite outdated ticket so probably the issue does not apply anymore. I will look into it and update the status of the ticket.

In the meantime if you are interested in supporting the project with some contributions, if you like please reach me on our community slack: community.globaleaks.org

Thank you!

**Comment by evilaliv3** [comment]
Hello @GuilhermeRameh , actually i confirm that this ticket is actually outdated.
