### ISSUE TITLE
Whistleblower Tip is given the ability to download a submitted file

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/globaleaks-whistleblowing-software#218]
The whistleblower cannot download a file from a Tip.

However in the Tip page there is a button "Download" for each of the file that he have upload.

The download button does not work.

This ticket is to remove the download button from whistleblower tip.

Screenshot attached:
![screen shot 2013-05-10 at 11 26 43 am](https://f.cloud.github.com/assets/770363/487311/c4559bb8-b953-11e2-8838-76835a5d9b0c.png)

**Comment by evilaliv3** [comment]
Update: in the context of the new laws of whistleblowing it has become necessary to make it possible for users to download their own submission to be able to prove they made a report and get back their own content if they dont have it anymore.

This original limitation has been then removed. 
For the moment there is no possibility to enable such a limit that is an option we might consider.
