### ISSUE TITLE
Error Message: Cannot read property 'steps' of undefined

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/globaleaks-whistleblowing-software#2191]
A production environment is triggering the exception "Error Message: TypeError: Cannot read property 'insertBefore' of null".

This seems to happen on the admin interface on the url: "/#/admin/questionnaires" in relation to $scope.triggerFieldDialog 

The setup is using version 3.0.2

**Comment by COLONAYUSH** [comment]
Hey @evilaliv3 
Is this issue still need resolving because I would like to work on that as my first issue

**Comment by evilaliv3** [comment]
Thank you @COLONAYUSH.

actually i'm not sure. I've not seen this anymore so i think it could have been solved in some of the changes we made.

**Comment by evilaliv3** [comment]
Closing as outdated.
