### ISSUE TITLE
"User preferences" label static (not translated dynamically)

### ISSUE THREAD

**Issue by moadr** [globaleaks/globaleaks-whistleblowing-software#2292]
**Current behavior**
In the "User Preferences" page, at the top of the page, label is always "User Preferences". 

**Expected behavior**
Is a minor issue, but if i change application language, label "User Preferences" should be translated. 

**GlobaLeaks version:**
3.0.29

**Comment by evilaliv3** [comment]
Thank you @moadr for reporting this.

I've reproduced the issue and the string appears to not be subject to internationalization.

**Comment by evilaliv3** [comment]
Patch issued, it will be released in next GlobaLeaks, version 3.1.0
