### ISSUE TITLE
Donation panel can not be disabled

### ISSUE THREAD

**Issue by elbill** [globaleaks/globaleaks-whistleblowing-software#2673]
Donation panel can not be disabled after update. While being disabled the donation panel appeared after the latest update. Admin settings don't change anything.
Donation panne should not appear since it is disabled.
updated from version: 3.10.8
to latest version: 3.11.1
Operating system Ubuntu 18.04LTS
client windows 10

**Comment by evilaliv3** [comment]
@elbill: Version 3.11.2 has been released and included the fix for this issue.
