### ISSUE TITLE
Add possibility to select own "Postpone expiration date"

### ISSUE THREAD

**Issue by schris-dk** [globaleaks/globaleaks-whistleblowing-software#3068]
It would be nice to have the feature to select your own expiration date.

We are facing a client, that want to be able to postpone expiration of case on a general basis to 12 months from the feedback to the whistleblower. Currently we can only choose the predefined shorter priod, which will leave a lot of administration work to follow up on this for each single case.

The current predefined period of time can be set as default, but it should be editable by the recipient.

**Comment by elbill** [comment]
Not any concerns whatsoever. Since the expiration date will be transparent
can't think of any GDPR or other issues. Maybe who postponed the report
could be audited however that may not be necessary.

**Comment by larrykind** [comment]
hello everyone, 
according to what @evilaliv3 says, jut one doubt for me:
if the extention time will be configurable, it should be avoided an infinitely delayed report by changing the configuration in the "background", bringing all the reports to the maximum available time.
Really agree with a per-context configuration.

**Comment by elbill** [comment]
Implementing this per report is a good idea for me. The user should have
the flexibility to postpone individual reports according to the GDPR
policy. Some reports may have to live in the system for two months, some
for a year even for more. This unusually has to do with the nature and the
content of the report, not the context.
The only problem I see is when someone postpones the report for a very long
time by accident and users do not have authorisation to delete reports.
There should be some way to reset the postponement.

**Comment by evilaliv3** [comment]
Thinking a little bit more about usability i would propose the following:
- i would not add a 'maximum' but I would just keep the configuration
possibilty as it is.
- i would use the current per context configuration policy to propose a
date
- i would make it possible to chose a shorter time below the default.
- i would not make it possible to choose a date that is longer with respect
to the context configuration.
- i would remove the possibility to postpone multiple submissions at once
so that users carefully will always do this operation after looking the
specific report and from the specific report page.

Do you think these changes could work?

**Comment by evilaliv3** [comment]
Here is a preview of the upcoming feature changes:

![Screenshot_2021-10-20 GLOBALEAKS - Report(1)](https://user-images.githubusercontent.com/217034/138075200-6906bb9c-7b02-465f-8ded-c5db58fe2325.png)

![Screenshot_2021-10-20 GLOBALEAKS - Report(2)](https://user-images.githubusercontent.com/217034/138075225-1677d8b5-535b-4645-8ddb-1c424cfaf619.png)

**Comment by schris-dk** [comment]
Looks great :-) - will definetely meet our requirements :-)

**Comment by evilaliv3** [comment]
Within the current implementation for security reasons i've considered to enforce the following constraints:
- The user could not choose a date before the existing expiration date
- The user could not choose a date that is above the preconfigured data retention policy.
