### ISSUE TITLE
implant so a lawyers can writte with a other lawyers throug globaleaks

### ISSUE THREAD

**Issue by strinux** [globaleaks/globaleaks-whistleblowing-software#3073]
Hi @evilaliv3, you doing a good job <3. 
I wanna ask if internale notes ever gone be a thing in globaleaks?

If You are about to leave a message, then you should have a option to save it as an internal note, so you can work together with a other recipent. 

Example: . You are about to leave the message as an internal note. That means that all recipent workers with access to the case will be able to see the message and can work together in a better way.

**Comment by evilaliv3** [comment]
Thank you for your feedback @strinux !

Actually this feature is already specified in https://github.com/globaleaks/GlobaLeaks/issues/2452
