### ISSUE TITLE
Unexpected exception in sendmail: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by giacomouberti** [globaleaks/globaleaks-whistleblowing-software#4077]
### What version of GlobaLeaks are you using?

4.15.3

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

We oftern receive notification from our users that the activation email for new receiver or admin account doesn't get to their inbox. We checked and emails are not being hold in quarantine or spam it appears like they are never sent by globaleaks.
If we try and test notification settings we get in the logs the following error while testing a custom SMTP server
`Unexpected exception in sendmail: can only concatenate str (not "NoneType") to str`

if we test with standard parameter we get another error as follows
`Starting factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x7fc7d4c5eb90>
Starting factory <globaleaks.utils.socks.SOCKS5ClientFactory object at 0x7fc800435870>
Stopping factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x7fc7d4c5eb90>
Stopping factory <globaleaks.utils.socks.SOCKS5ClientFactory object at 0x7fc800435870>`

The errors has happened also before the most recent upgrade and when rebooting the server all emails that appear to be "stacked" got sent in bulk also with some expired notification causing some misunderstaing with clients.

**Comment by evilaliv3** [comment]
Thank you @giacomouberti 

I'm sorry for the delay in this answer, apparently this ticket remained unchecked.

Are you still encountering this issue? Are you able to test release 5 and see if it does still apply?

**Comment by giacomouberti** [comment]
Hi there @evilaliv3 by october 31st we have a scheduled maintenance planned and we'll upgrade to release 5 in the testing environment and I'll come back to you and update if we have benn able to solve the issue or still need assistance. Thanks

**Comment by giacomouberti** [comment]
Hi there @evilaliv3 sorry for the late reply,
after the update to version 5.0.20 we tested the configuration with custom AWS SES credentials and the email went through and we didn't identify any error in the logs resulting in
```
2024-11-11 12:06:07+0000 [-] Starting factory _HTTP11ClientFactory(<function HTTPConnectionPool._newConnection.<locals>.quiescentCallback at #x###########>, <twisted.internet.e
ndpoints._WrapperEndpoint object at #x###########>)
2024-11-11 12:06:07+0000 [-] Stopping factory _HTTP11ClientFactory(<function HTTPConnectionPool._newConnection.<locals>.quiescentCallback at #x###########>, <twisted.internet.e
ndpoints._WrapperEndpoint object at #x###########>)
2024-11-11 12:10:13+0000 [-] Starting factory <twisted.mail.smtp.ESMTPSenderFactory object at #x###########>
2024-11-11 12:10:14+0000 [-] Stopping factory <twisted.mail.smtp.ESMTPSenderFactory object at #x###########>
```
