### ISSUE TITLE
GPG Error: The repository is not signed 

### ISSUE THREAD

**Issue by Fourmarketing360** [GLOBALEAKS/globaleaks-whistleblowing-software#4235]
### What version of GlobaLeaks are you using?

5.015

### What browser(s) are you seeing the problem on?

Other

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

Trying to install Globaleaks following the installation guide and it gives the following error:

GPG error: https://deb.globaleaks.org jammy/ Release: The following signatures were invalid: BADSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
E: The repository 'http://deb.globaleaks.org jammy/ Release' is not signed.

Saw an old thread about this and it seems some key of yours did not get its validation extended

### Proposed solution

Extend key validation

**Comment by evilaliv3** [comment]
Thank you @Fourmarketing360 , actually in the moment you tried to install we were releasing an update so the repository was requiring to be signed.
