### ISSUE TITLE
Can't Update Globaleaks

### ISSUE THREAD

**Issue by nicogithub22** [globaleaks/globaleaks-whistleblowing-software#4238]
### What version of GlobaLeaks are you using?

4.14.8

### What operating system(s) are you seeing the problem on?

Windows, Linux

### Describe the issue

I try to update Globaleaks with sudo apt upgrade and get the following error message:
Error:7 https://deb.globaleaks.org jammy/ Release.gpg
The following signatures were invalid: EXPKEYSIG 32E6792624045008 GlobaLeaks software signing key 
.....
W: An error occurred while verifying the signature. The vault has not been updated and the previous index files are being used. GPG error: https://deb.globaleaks.org jammy/ Release: The following signatures were invalid: EXPKEYSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
W: Failed to fetch from http://deb.globaleaks.org/jammy/Release.gpg The following signatures were invalid: EXPKEYSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
W: Some index files could not be downloaded. They were ignored or old ones were used in their place.

### Proposed solution

I then changed the file as a test:
deb [trusted=yes] https://deb.globaleaks.org jammy/

I was then able to install the latest version, but the login to the GUI in the web browser no longer worked.

**Comment by evilaliv3** [comment]
Thank you @nicogithub22, the solution is indicated in: https://github.com/globaleaks/globaleaks-whistleblowing-software/issues/4040

Please try to look for existing issues before opening new ones if possible.
