### ISSUE TITLE
Thank you @nicogithub22, the solution is indicated in: https://github.com/globaleaks/globaleaks-whistleblowing-software/issues/4040

### ISSUE THREAD

**Issue by nicogithub22** [globaleaks/globaleaks-whistleblowing-software#4247]
Thank you @nicogithub22, the solution is indicated in: https://github.com/globaleaks/globaleaks-whistleblowing-software/issues/4040

Please try to look for existing issues before opening new ones if possible.

_Originally posted by @evilaliv3 in https://github.com/globaleaks/globaleaks-whistleblowing-software/issues/4238#issuecomment-2416057368_

**Comment by nicogithub22** [comment]
do not work :
To resolve issue:
rm /etc/apt/trusted.gpg
wget -qO- https://deb.globaleaks.org/globaleaks.asc | gpg --dearmor >
/etc/apt/trusted.gpg.d/globaleaks.gpg
apt-get update

**Comment by nicogithub22** [comment]
please help @evilaliv3 
still the same issue

**Comment by evilaliv3** [comment]
@nicogithub22 : this is really not the way of using this ticketing system and asking support. This is not polite spamming and wasting community resources.
