### ISSUE TITLE
migrating globaleaks to new debian

### ISSUE THREAD

**Issue by FFD8FFE1** [globaleaks/globaleaks-whistleblowing-software#4276]
### Discussed in https://github.com/orgs/globaleaks/discussions/4275

<div type='discussions-op-text'>

<sup>Originally posted by **FFD8FFE1** October 21, 2024</sup>
hi i have created a new debian VM and i have followed the migration guide
https://docs.globaleaks.org/en/main/user/admin/UpgradeGuide.html

i have extracted the backup of the globaleaks folder to /var/globaleaks  the backup is from a globaleaks system ver. 5.0.17, and the database i detected as version 68

when i run the globalkeaks install script 5.0.18 it creates a lot of errors

 have tested that the install method works when there is no backup of old data.
wget https://deb.globaleaks.org/install-globaleaks.sh
chmod +x install-globaleaks.sh
./install-globaleaks.sh

i have attached the error log with masked url´s

i hope you can help me migrate, since the described method doesn't work in my case.

Thanks in advance
[migrate_error_log.txt](https://github.com/user-attachments/files/17458786/migrate_error_log.txt)

</div>

**Comment by FFD8FFE1** [comment]
hi the server shut down, (it also did the exact same thing on a physical ubuntu laptop.)

**Comment by FFD8FFE1** [comment]
hi i just tested with a backup of an other globaleaks system. 

the backup was transfered to an other brand new vm with 8 GB of memory and 5 logical cpu´s (debian 12 command line only.)

i did not change owner of the files, i extracted with tar -xvzf, and then copy (cp -r /globaleaks /var/globaleaks)

i got the same issue:

2024-10-21 06:57:24+0000 [-] Stopping factory <Site object at 0x7feea77ab7b8>
2024-10-21 06:57:24+0000 [-] [E] Exception while running Tor
2024-10-21 06:57:24+0000 [-] Traceback (most recent call last):
2024-10-21 06:57:24+0000 [-]   File "/usr/lib/python3/dist-packages/globaleaks/services/service.py", line 25, in run
2024-10-21 06:57:24+0000 [-]     yield self.operation()
2024-10-21 06:57:24+0000 [-] twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2024-10-21 06:57:24+0000 [-] [E] exception mail suppressed for exception (<class 'twisted.internet.error.ConnectionLost'>) [reason: special exception]
2024-10-21 06:57:24+0000 [-] Server Shut Down.

**Comment by evilaliv3** [comment]
Do you see see errors in dmesg? I wonder if the operating system is killing the process for some reasons.

**Comment by FFD8FFE1** [comment]
i have now removed globaleaks and inserted the backup, and installed globaleaks via apt install


apt remove globaleaks
apt autoremove
sudo rm -rf /var/globaleaks
sudo cp -r var/globaleaks /var/globaleaks

apt install globaleaks

now i get this error:

Setting up python3-twisted (22.4.0-4) ...
Setting up python3-txtorcon (22.0.0-1) ...
Setting up globaleaks (5.0.18) ...
Could not execute systemctl:  at /usr/bin/deb-systemd-invoke line 145.
Processing triggers for man-db (2.11.2-2) ...
Processing triggers for libc-bin (2.36-9+deb12u8) ...
