### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by Ridon77** [globaleaks/globaleaks-whistleblowing-software#4282]
### What version of GlobaLeaks are you using?

5.0.18

### What browser(s) are you seeing the problem on?

Chrome

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

Using the text costumization (Spanish) The following texts are not translated in the site:

· Seleccione un canal de denuncias: (Select a reporting channel:)
· Presentar una denuncia. (File a report)

I send screenshots describing the issue
![FileAReport1](https://github.com/user-attachments/assets/bc9ba74c-5404-4708-91f8-f04a9e25d916)
![FileAReport2](https://github.com/user-attachments/assets/6638c93e-cdf8-4bdf-9814-05b01a442efc)

![ReportingChanel1](https://github.com/user-attachments/assets/6ae0362b-6d7f-4b07-9546-2f6fff664524)
![ReportingChanel2](https://github.com/user-attachments/assets/b0e99764-104d-4320-a3ae-0252f69ae0fb)

### Proposed solution

These items are wel translated if use the english language.

Other Items are well translated using the same text costumization option.

**Comment by evilaliv3** [comment]
Hello @Ridon77,

The feature you are trying to use to override the translations does work only for the platform texts that do not have a specific configuration section; In this case the text that you are customizing can be directly customized it the general settings of the application.

I would like as well to point out that the software translations are officially managed on [transifex](https://app.transifex.com/otf/globaleaks/)
Do you consider that "File a report" is incorrectly translated and would you like to propose a translation change or do you want just to customize this? 


If you just want to customize your text you could do it in the general settings of the plaftorm.

**Comment by Ridon77** [comment]
Thank you.

The translation is correct. We are changing some terms just to adapt to pur specific policy in the company.

Thank You
