### ISSUE TITLE
"You must select at least one recipient" and the sending of the report is blocked 

### ISSUE THREAD

**Issue by paolotomiato** [globaleaks/globaleaks-whistleblowing-software#4288]
### What version of GlobaLeaks are you using?

5.0.20

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What operating system(s) are you seeing the problem on?

Windows, Linux

### Describe the issue

When trying to send a report the system returns the message "You must select at least one recipient" but in the form there is no choice regarding the choice of recipient.
In the portal configuration there is only one registered recipient.

**Comment by evilaliv3** [comment]
Hello @paolotomiato , thank you

I think you may have forgot to add at least one recipient to your reporting channel.

Reconfigure your reporting channel adding at least one recipient to resolve your configuration issue.

**Comment by paolotomiato** [comment]
Thanks Giovanni for the quick reply... well... maybe I didn't understand a damn thing, these are the registered users:
![Schermata del 2024-11-01 15-01-21](https://github.com/user-attachments/assets/241470bb-7b70-4149-a6f5-222d0a6808c9)
It seems to me that the recipient is there...

**Comment by evilaliv3** [comment]
Open the Channel section, locate the default channel and add your
recipients to it.

**Comment by paolotomiato** [comment]
Many thanks Giovanni, it's clear to me now!
