### ISSUE TITLE
Update Error - Signature Verification

### ISSUE THREAD

**Issue by nicogithub22** [globaleaks/globaleaks-whistleblowing-software#4294]
### What version of GlobaLeaks are you using?

Softwareversion: 4.14.8

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

I am trying to update from 4.14.8 to 5.0.21. I am using Ubuntu 22.04.4 LTS. You can see error below:

root@hinschg-meldestelle:/home/admin-hinschg# apt-get update
OK:2 http://de.archive.ubuntu.com/ubuntu jammy InRelease
Ign:1 https://deb.globaleaks.org jammy/ InRelease
Holen:3 https://deb.globaleaks.org jammy/ Release [741 B]
Holen:4 https://deb.globaleaks.org jammy/ Release.gpg [833 B]
Holen:5 http://de.archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
**Fehl:4 https://deb.globaleaks.org jammy/ Release.gpg**
  **Die folgenden Signaturen waren ungültig: EXPKEYSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>**
...
W: An error occurred while checking the signature. The depot was not updated and the previous index files are used. GPG error: https://deb.globaleaks.org jammy/ Release: The following signatures were invalid: EXPKEYSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
W: http://de.archive.ubuntu.com/ubuntu/dists/jammy-updates/main/i18n/by-hash/SHA256/f5fee7e9a33a3a534b17053a54294bf4359b124f73efe17281cc850980e5f8ea: Acquire::http::Pipeline-Depth function automatically disabled due to incorrect response from server/proxy. See apt.conf(5) for details.
W: Failed to fetch http://deb.globaleaks.org/jammy/Release.gpg The following signatures were invalid: EXPKEYSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
W: Some index files could not be downloaded. They were ignored or old ones were used in their place.

Can someone perhaps give me a tip on what else I could do?

### Proposed solution

- I tried the solution from: #4040

**Comment by evilaliv3** [comment]
Thank you @nicogithub22 . We are doing some maintenance and the issue should be solved by today.
