### ISSUE TITLE
Missing error alert if user inserts a wrong Recovery Key 

### ISSUE THREAD

**Issue by eleibr** [globaleaks/globaleaks-whistleblowing-software#4297]
### What version of GlobaLeaks are you using?

4.13.11
4.15.9

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### Describe the issue

When making the password recovery request, if you enter a wrong Recovery Key, the system does not return any error message, but the modal dialog remains open, with the field for entering the text blanked out. In this way the user cannot notice if the key in his possession is incorrect.
These operations are not tracked in the application log.

![rk1](https://github.com/user-attachments/assets/e9376ea4-ee4b-4de5-bc22-49d5cdd73b4a)
![rk2](https://github.com/user-attachments/assets/4bf7637b-dfb4-4034-87ce-29c7c20021eb)

This is extremely misleading because neither the user nor the Administrator can understand if the recovery key is incorrect or compromised

### Proposed solution

Show an error to the user

**Comment by evilaliv3** [comment]
Thank you @eleibr , we have just corrected this in releae 5.0.25
