### ISSUE TITLE
Customization of non customizable text like "Select a reporting channel:

### ISSUE THREAD

**Issue by elbill** [globaleaks/globaleaks-whistleblowing-software#4307]
### Proposal

There are specific text sections that can not be customized like for example "Select a reporting channel:"
Alternatively can text be replaced with javascript for various languages? Can you please provide an example for the above text. 

### Motivation and context

Ïn several occasions the text needs to be customised according to specific needs as most text in the platform.

**Comment by evilaliv3** [comment]
Hello @elbill 

Actually this text is currently specifically configurable in the advanced setting.

Some interfaces like this in fact benefit of a specific configuration section.

I know it is confusing at the moment that we have two different ways of configuring texts and we should probably think if to use the text customization section for every default text of the application.
