### ISSUE TITLE
Faillure on validation on emails with .tld  longer than 5 characters

### ISSUE THREAD

**Issue by dapatas** [globaleaks/globaleaks-whistleblowing-software#4309]
### What version of GlobaLeaks are you using?

5.0.24

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

Notifications: wrong warning message using domain .online 
changing with .it or .com the warning disappears (see screenshot %170743%)

![Screenshot 2024-11-12 170700](https://github.com/user-attachments/assets/544ed84d-5a0f-4665-be55-2b41b26addaf)
![Screenshot 2024-11-12 170743](https://github.com/user-attachments/assets/00263d30-34f4-4668-8f99-069c00a5e04e)

**Comment by evilaliv3** [comment]
Thank you for reporting this @dapatas 
The issue is now solved.

**Comment by dapatas** [comment]
Thanks a lot!
