### ISSUE TITLE
Failed preview of an attached file

### ISSUE THREAD

**Issue by marcopvl** [globaleaks/globaleaks-whistleblowing-software#4312]
### What version of GlobaLeaks are you using?

5.0.25

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

The preview of an attached file is missing, like in the attached image.
Please could you check ?

Thanks

![anomalia-anteprima-file](https://github.com/user-attachments/assets/b8f08a38-c073-468e-a130-0ea90e726ea7)

**Comment by evilaliv3** [comment]
Thank you @marcopvl, this has been already noticed and should be fixed in 5.0.26.

Would you please check?

**Comment by marcopvl** [comment]
Thanks @evilaliv3 the preview's problem was fixed in version 5.0.26
