### ISSUE TITLE
Major bug in 5.0.27 - page contents in questionaires are not shown

### ISSUE THREAD

**Issue by schris-dk** [globaleaks/globaleaks-whistleblowing-software#4321]
### What version of GlobaLeaks are you using?

5.0.27

### What browser(s) are you seeing the problem on?

N/A

### What operating system(s) are you seeing the problem on?

N/A

### Describe the issue

After upgrading our test environment, content on different pages are not shown anymore

![image](https://github.com/user-attachments/assets/352140a9-afb8-4a30-a0f8-dc6e0fa85f7d)

### Proposed solution

?

**Comment by evilaliv3** [comment]
@schris-dk : this seems very specific to the features used in your questionnaire.

Would you please provide a copy of it to see which are the failing features?

**Comment by evilaliv3** [comment]
@msmannan00: would you please check on this when @schris-dk will provide the questionnaire?

**Comment by msmannan00** [comment]
Yes definitely, will try to patch a fix as soon as I have the questionnaire

**Comment by simohks** [comment]
The issue is reproduced in version 5.0.26 as well. 5.0.25 no issue with the questionnaires.

**Comment by simohks** [comment]
If you choose not to leave any contact details and click next.

![image](https://github.com/user-attachments/assets/302856e4-2cbe-4261-b1b8-d4fc612b7be2)

The multi-line text input and the attachment  sections are not visible.

![image](https://github.com/user-attachments/assets/f427562c-b061-4d40-83e8-b818320ca1da)

If you choose to leave contact details then on a next page you are able to see the missing sections.

**Comment by evilaliv3** [comment]
ok but introduced in 5.0.26 with commit: https://github.com/globaleaks/globaleaks-whistleblowing-software/commit/6fc9d905ee26ef82fd4afda2c03867f6486522c4

We are going to issue a fix and include it by today in a minor release 5.0.29

**Comment by evilaliv3** [comment]
Thank you @schris-dk  and @simohks for your prompt feedback!

**Comment by msmannan00** [comment]
Noted, if need any support in this please do tell

**Comment by clsbn** [comment]
Hi, same problem with 5.0.28. Attached is my questionnaire. 
[Segnalazioni Whistleblowing.json](https://github.com/user-attachments/files/17921090/Segnalazioni.Whistleblowing.json)

In #4334 some images.
Thank you
