### ISSUE TITLE
Unable to submit a questionnaire form

### ISSUE THREAD

**Issue by simohks** [globaleaks/globaleaks-whistleblowing-software#4335]
### What version of GlobaLeaks are you using?

5.0.29

### What browser(s) are you seeing the problem on?

N/A

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

Related to an issue 4321 when a questionnaire form was not visible if not leaving contact details. After upgrading to 5.0.29 the questionnaire form is visible if not leaving contact details but the submit button is not working.

**Comment by simohks** [comment]
Thank you for a quick response

**Comment by evilaliv3** [comment]
@simohks at the moment i'm not able to reproduce the issue.

Are you sure you have filed all the mandatory questions?

The questionnaire in my tests prevent to submit the questions only if the questionnaire is not filed completely

**Comment by evilaliv3** [comment]
We are issuing a release 5.0.30 that should fix the issues reported here by removing the changes that enforced checks on mandatory file uoploads that seems to have caused this regression and we will postpone such a feature integration to a later stage.
