### ISSUE TITLE
Implement mandatory checks on file uploads and voice messages

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/globaleaks-whistleblowing-software#4336]
This ticket is to keep track of the work necessary to enforce mandatory checks on file uploads and voice messages.

**Comment by evilaliv3** [comment]
I think with the new angular, we need to implement some sort of custom validator to ensure that a user can complete a submission only if at least one file has been loaded on a file upload question or a voice message question when they are marked as mandatory.

Currently we are showing an error, but the submission is proceeding to completion.

**Comment by evilaliv3** [comment]
@msmannan00 would you please give a look a this ensuring it works with questionnaires configured with multiple steps where one of the step contains a question of type file upload marked mandatory and as well if one of the steps contains a voice question marked mandatory?

**Comment by msmannan00** [comment]
Hmm, this might be the issue skipped, sure will look into it.

**Comment by evilaliv3** [comment]
The fix implemented by @msmannan00 will be included in release 5.0.32
