### ISSUE TITLE
Recipient public names appear in recipient case management

### ISSUE THREAD

**Issue by elbill** [globaleaks/globaleaks-whistleblowing-software#4338]
### What version of GlobaLeaks are you using?

5.0.29

### What browser(s) are you seeing the problem on?

Chrome

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

Recipients when trying to grant or revoke access they see the public name. This makes it very confusing as most public names are generic and do not know who to allocate to.

**Comment by evilaliv3** [comment]
Thank you for reporting this @elbill . We will try to fix this already in the next minor releases.

**Comment by elbill** [comment]
@evilaliv3  has this been fixed in 5.0.31? If not any idea when or can we do any rollback? Thanks

**Comment by evilaliv3** [comment]
No but i'm trying to make a fix to be included by the weekend in a 5.0.32
