### ISSUE TITLE
Links are not active in text message when blocking a report or when showing information for selection questions.

### ISSUE THREAD

**Issue by elbill** [globaleaks/globaleaks-whistleblowing-software#4340]
### What version of GlobaLeaks are you using?

5.0.29

### What browser(s) are you seeing the problem on?

Chrome

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

When setting a selection question to block a report in version 4, links appeared active and clickable.
In version 5 it is just text.
I think that was the case also for information text on selections.
![image](https://github.com/user-attachments/assets/ed241988-17ad-49d5-ba04-410d3b0a80ce)

### Proposed solution

It is very important to reactivate this feature as we have planforms that when blocking the report, you give them the option to be redirected to the alternative authority that is suitable for this type of report, through a link and not to have to copy paste text in browser.
Same with information text for selections.
The links can be just links or markdown.

**Comment by evilaliv3** [comment]
Thank you @elbill , probably if you use markdown you can get this fixed right away.

I'm going to check if the component we are using in the current version can anyhow handle this aspect automatically like the previous.

**Comment by elbill** [comment]
Indeed. Markdown would be useful, however a quick patch would be appreciated!

**Comment by evilaliv3** [comment]
Fix to be included in release 5.0.32
