### ISSUE TITLE
On release 5 injection of images via Markdown seem not working

### ISSUE THREAD

**Issue by elbill** [globaleaks/globaleaks-whistleblowing-software#4341]
### What version of GlobaLeaks are you using?

5.0.32

### What browser(s) are you seeing the problem on?

Chrome

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

In version 4 markdown was enabled in question descriptions. This is no longer the case and only links show active as pached following issue #4340. I had some markdown implementations in description showing odd now.

### Proposed solution

I would suggest bringing back markdown in question descriptions as well as enabling it in other elements such as information showing after selecting specific question and blocked question.

**Comment by evilaliv3** [comment]
@elbill : actually markdown is enabled on question description.

would you please provide an example of the syntax that you are using and the output that you are getting?

**Comment by elbill** [comment]
It used to render the images as links to an external platform. now the markdown code shows as in the example

[![Doping Cipher](/s/dopingen.png)](https://www.interactrapp.com/share/63c00cd608758)

![image](https://github.com/user-attachments/assets/85722fb0-03c0-4ec3-acb2-f94a0faa0101)

![image](https://github.com/user-attachments/assets/4bbaeba2-ced5-430f-a62c-06390dafbcc5)

**Comment by elbill** [comment]
So i was using thumdnails as links to external elearning content. The thumbnail images dont show any more.

**Comment by evilaliv3** [comment]
Are you using markdown or html?

Maybe you were using some html tags and the old component was accepting it?

**Comment by elbill** [comment]
"[![Doping Cipher](/s/dopingen.png)](https://www.interactrapp.com/share/63c00cd608758)"

**Comment by elbill** [comment]
havent made any modification in CSP.
please check:
https://fraudline.try.globaleaks.org/#/
landing page and questionaire
I'm providing password in slack

**Comment by evilaliv3** [comment]
Thank you.

The bug comes from the combination of images and links and seems to be related to this commit: https://github.com/globaleaks/globaleaks-whistleblowing-software/commit/a6bd235fd84b344b6b11718cefa1ccad806ac72e

**Comment by evilaliv3** [comment]
Corrected and the fix will be included in 5.0.33
