### ISSUE TITLE
Information icon that the whistleblower has read/not read the latest update not working properly

### ISSUE THREAD

**Issue by elbill** [globaleaks/globaleaks-whistleblowing-software#4344]
### What version of GlobaLeaks are you using?

5.0.31

### What browser(s) are you seeing the problem on?

Chrome

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

As soon as  teh whistleblower reads the first update then even if we send further messages the checkpoint will not change state.
![image](https://github.com/user-attachments/assets/0eae19b8-4656-4bf9-8a70-3d4449463332)

### Proposed solution

This should be fixed. As soon as we send an update, this should chnge state to unread, till the whistleblower sees the update

**Comment by elbill** [comment]
seems that the latest update date is not updated.

**Comment by elbill** [comment]
![image](https://github.com/user-attachments/assets/70561b16-b3e7-41e0-9ccd-e5dfaa8536e6)

**Comment by evilaliv3** [comment]
Thank you, bug confirmed. Going to issue a patch to be included in release 5.0.33
