### ISSUE TITLE
v5.0.32 issue - Recipients unable to upload attachments to submissions

### ISSUE THREAD

**Issue by aetdr** [globaleaks/globaleaks-whistleblowing-software#4349]
### What version of GlobaLeaks are you using?

v5.0.32

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows, N/A

### Describe the issue

Hi @evilaliv3 

With the newest release, recipients are not able to upload attachments to submissions.
The "Upload" button is grayed out for all recipients.

**Comment by aetdr** [comment]
@evilaliv3 

You are right. It works if something is written in the description field.

It is not really intuitive as one expects from experience that the field right before the button should contain the choosen file path and not description. 

This confuses many, maybe you could improve it a bit. Maybe placing the description on a separate line with * required mark

**Comment by evilaliv3** [comment]
Thank you for your feedback, we are aware of this. Some of this functionalities were implemented low budget and would definitely need some reworks.

If you have customers that could support some development please consider donating to the project . Thank you for evaluating this possibility.
