### ISSUE TITLE
Issue with granting access to a submission to other recipients

### ISSUE THREAD

**Issue by aetdr** [globaleaks/globaleaks-whistleblowing-software#4352]
### What version of GlobaLeaks are you using?

most recent

### What browser(s) are you seeing the problem on?

Chrome

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

Hi @evilaliv3 

A recipent can give acces to a submission to other recipients. 
There are following issues with the granting UI:

- The list is populated with public recipient names. These names are intended to be seen by whistleblowers and are usually anonymized. This makes it difficult to find the rigth person to give access to. 
I would expect to see real names instead.

- The width of the dropdown meny with names is too narrow. Names are heavily truncated. I would expect the list to be as wide as the longest name on it.

**Comment by evilaliv3** [comment]
Thank you @aetdr 

The first topic reported should be already solved in latest release. Which version are you running?

We will be checking on the other matter.

**Comment by evilaliv3** [comment]
Closing, the fix to the size will be included in release 5.0.37
