### ISSUE TITLE
custom url for languages?

### ISSUE THREAD

**Issue by mapreri** [globaleaks/globaleaks-whistleblowing-software#4353]
### What version of GlobaLeaks are you using?

5.0.34

### What operating system(s) are you seeing the problem on?

N/A

### Describe the issue

There was this feature which let people reach a localized version with a defined URL, i.e.

http://demo.globaleaks.org/#/it
http://demo.globaleaks.org/#/en

this was done as part of https://github.com/globaleaks/globaleaks-whistleblowing-software/issues/778

Apparently that is not working with current versions of globaleaks.  Was that feature retracted?  Any alternative?

**Comment by evilaliv3** [comment]
Hello @mapreri 

You could use ?lang=$lang for example ?lang=en for english and ?lang=it for italian
