### ISSUE TITLE
Check point tick for "whistleblower has already read the latest update" still not working properly

### ISSUE THREAD

**Issue by elbill** [globaleaks/globaleaks-whistleblowing-software#4366]
### What version of GlobaLeaks are you using?

5.0.41

### What browser(s) are you seeing the problem on?

Chrome

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

There is often that despite there has been a new comment from recipents, the tick remains and does not conver to x.
I'm sending an example that managed to recrete from older test reports. The example is just a small time differece, however the client has shown me similar cases with diffences in dates.
![Uploading 20241223_150715.jpg…]()

![20241223_150649](https://github.com/user-attachments/assets/178fbf01-1316-4165-b15d-a67c389d1f0d)

**Comment by elbill** [comment]
![20241223_150715](https://github.com/user-attachments/assets/ee4d6146-4cb1-4b47-a11d-c2f416b7f4b9)

**Comment by evilaliv3** [comment]
Thank you @elbill 

These seems the same images that you loaded on https://github.com/globaleaks/globaleaks-whistleblowing-software/issues/4344

The bug was solved but the fix applies only to new comments.

Do you have evidences where the bug happened again on new reports/comments?

**Comment by elbill** [comment]
Indeed... for some reason I could not find the old case...
I'm trying to contact with the customer that reported this to clarify.
Is there some way to be fixed for older cases as well?

**Comment by elbill** [comment]
Just confirmed the last report this occure was before the fix.
Is there some way to fix the checkoints for older reports?

**Comment by evilaliv3** [comment]
yes, you could manually fix this if set the last update of the report to thecreation_date of the last message or file loaded on the platform.

**Comment by elbill** [comment]
thanks @evilaliv3 . Do you need to modify the database for this? Is this a fix that could be included in the next release?

**Comment by evilaliv3** [comment]
hello @elbill, as reported in this comment (https://github.com/globaleaks/globaleaks-whistleblowing-software/issues/4366#issuecomment-2561117310) an automatic fix would be complicated and risky. If you really need it you can just set the last update of the report to thecreation_date of the last message or file loaded on the platform.
