### ISSUE TITLE
Enable sending submission fields & comments via email if encryption notification is enabled

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/globaleaks-whistleblowing-software#484]
Enable sending submission fields & comments via email if encryption notification is enabled .

This requests has been raised by an adopter that would like to have quick spooling of submission via email, without having to log-in to globaleaks, in order to quickly identify if there's something interesting.

**Comment by evilaliv3** [comment]
Marking this explicitly as discarded. Such an implementation, leading to possibly store content permanently in the mailbox of users would vanish any effort made to enable strong data retention policies.
