### ISSUE TITLE
Integrate Ahmia Linked Data Proposal for TorHS

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/globaleaks-whistleblowing-software#493]
Integrate Ahmia Linked Data Proposal for TorHS

This ticket is to brainstorm integration of https://ahmia.fi/documentation/descriptionProposal/

**Comment by evilaliv3** [comment]
@juhanurmi: it seems to me that this is something no more used, am i right?

is there any plan to support it in the future or you evaluated to drop this specification?
