### ISSUE TITLE
Receiver only comments

### ISSUE THREAD

**Issue by vecna** [globaleaks/globaleaks-whistleblowing-software#512]
As requested by Partner-X, its needed an interface to permit receiver only comments.

there are various approach, can be:
- specify a recipient of the comment (single receiver | all receiver | all receiver + wb)
- have differents comments list (all receivers on the left, and all receivers+wb on the right)

**Comment by evilaliv3** [comment]
This was actually really implemented only in 2023 funded by ANAC: https://github.com/globaleaks/globaleaks-whistleblowing-software/issues/2452
